# Generated by Django 6.0.2 on 2026-02-26 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='customer_email',
            field=models.EmailField(db_comment='Email de contacto del cliente', default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='party_size',
            field=models.PositiveSmallIntegerField(db_comment='Cantidad de personas asociadas a la reserva', default=1),
        ),
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(db_comment='Estado actual de la reserva', default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='customer_name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_date',
            field=models.DateField(),
        ),
    ]
