# Generated by Django 6.0.2 on 2026-02-26 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_reservation_customer_email_reservation_party_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='customer_name',
        ),
        migrations.AddField(
            model_name='reservation',
            name='contact_name',
            field=models.CharField(db_comment='Nombre de contacto principal', default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='customer_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='party_size',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_date',
            field=models.DateField(db_comment='Fecha efectiva de la reserva'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], db_comment='Estado controlado de la reserva', default='PENDING', max_length=20),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['reservation_date'], name='idx_reservation_date'),
        ),
    ]
