# Generated by Django 6.0.2 on 2026-02-26 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_remove_reservation_customer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_comment='Última modificación del registro'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='contact_name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='customer_email',
            field=models.EmailField(db_comment='Email obligatorio para notificaciones', max_length=254),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['status'], name='idx_reservation_status'),
        ),
    ]
